### ISSUE TITLE
[Question] What is the difference between token access and other resources in ACL?

### ISSUE THREAD

**Issue by longshine** [gravitational/webapps#1374]
Hi team, I got really confused when I tried to add a role with verb `create` on resource `node`, expecting that the role could see `add` button enabled on the Node page, but could never make it work.

I noticed that `getTokenAccess()` is used in node/app/db/... pages instead of their own ACL object like `getNodeAccess()`, and I did not found any explanation on the documentation.

https://github.com/gravitational/webapps/blob/bb55c7b4c4e6b8b1c366a38704cc472e30a83b0a/packages/teleport/src/Nodes/useNodes.ts#L41

**Comment by kimlisa** [comment]
Hi @longshine, sorry about the late reply!

It's a bit hidden, but the reason why token access is necessary is because in order to add new resources to Teleport, you'll need to create a [join token](https://goteleport.com/docs/server-access/getting-started/#create-a-join-token) to establish trust between Teleport cluster and your new resource. And we create the token for you on our web UI (if you have the token `create` access). 

Our pre-built role `editor` should include this rule already. Hope this made sense!

**Comment by wadells** [comment]
All the code in this repo has been moved to https://github.com/gravitational/teleport/tree/master/web. Any future issues should be opened in that repo.

I'm going to close this for now, in anticipation of archiving this repo soon.  Please leave a note if there is still a need for this issue.
