### ISSUE TITLE
[Teleport Connect ] Can't login to Teleport cluster using TOTP method

### ISSUE THREAD

**Issue by sshahcodes** [gravitational/webapps#793]
The Teleport Connect is throwing error while login into Teleport cluster using TOTP code as a 2FA method. Hardware Token works fine.  

Expected behavior:
Should be able to login using TOTP method for 2FA.

Current behavior:
<img width="1175" alt="Screen Shot 2022-04-29 at 12 12 33 PM" src="https://user-images.githubusercontent.com/10177602/165895123-24605199-05df-4bd1-9d64-bc74b909b027.png">

Bug details:
- Teleport version: Teleport v9.1.2 git:v9.1.2-0-geef8b5ac6 go1.17.9
- Recreation steps: [Download and install Teleport Connect](https://drive.google.com/file/d/1TYLeJ_l_R_2dQ7-3EsabYUK9piv8VW7-/view) (Preview). Try to connect a new cluster with TOTP code as 2FA method

**Comment by ravicious** [comment]
I was able to reproduce this too. I'm looking into that right now.

**Comment by ravicious** [comment]
@sshahcodes Is your `second_factor` setting of the auth service set to `optional`?

**Comment by ravicious** [comment]
If `second_factor` is set to `on` or `optional`, Connect uses `SSHAgentMFALogin` rather than `SSHAgentLogin`, which is exactly the same logic as tsh uses.


https://github.com/gravitational/teleport/blob/8e0421e39b49d0c8907e42e44e5a1d6bd6112df8/lib/teleterm/clusters/cluster_auth.go#L93-L106

However, the OTP token isn't passed to `SSHAgentMFALogin`. So when tsh sees that you want to use OTP, it asks you to provide the token via stdin. Matter of fact, you can see that for yourself if you launch Connect from the terminal.

A potential solution would be to have a separate case branch for `on` and `optional` where we'd check if we have an OTP token. If yes, then we'd use `SSHAgentLogin`, if not then `SSHAgentMFALogin`. I'm not sure if this is not going to break some auth methods though.

We're investigating right now how the Web UI deals with this.

**Comment by sshahcodes** [comment]
Yes my `second_factor` was set to `on`.
