### ISSUE TITLE
Prettier fixes

### ISSUE THREAD

**Issue by michellescripts** [gravitational/webapps#887]
**What**
- add a pre-commit hook to check changed files for prettier formatting (i.e., prevent commits with improper formatting)
- see if there are any files with existing errors that can be fixed without introducing errors
- re-run snapshots for tests that break (likely to see this with design files that are missing leading zeros)

**Why**
- clean code, enforced!

**Comment by ravicious** [comment]
> add a pre-commit hook to check changed files for prettier formatting (i.e., prevent commits with improper formatting)

What do you think about adding a linter rule for that instead of a pre-commit hook? The linter must be satisfied before merging a PR to the main branch. Most of the time we do squash and merge, so this would ensure that the tip of the main branch is formatted correctly.

IMHO, pre-commit hooks are a rather invasive way to take care of this. I wouldn't want to be prevented from making a commit by a problem that can be fixed after the fact (before the PR is merged).
